import * as THREE from "three/webgpu"

export const createRoundedRectangleGeometry = (x: number, y: number, width: number, height: number, radius: number): THREE.ShapeGeometry => {
  const roundedRectShape = new THREE.Shape();
	roundedRectShape.moveTo( x, y + radius );
	roundedRectShape.lineTo( x, y + height - radius );
	roundedRectShape.quadraticCurveTo( x, y + height, x + radius, y + height );
	roundedRectShape.lineTo( x + width - radius, y + height );
	roundedRectShape.quadraticCurveTo( x + width, y + height, x + width, y + height - radius );
	roundedRectShape.lineTo( x + width, y + radius );
	roundedRectShape.quadraticCurveTo( x + width, y, x + width - radius, y );
	roundedRectShape.lineTo( x + radius, y );
  roundedRectShape.quadraticCurveTo(x, y, x, y + radius);

  return new THREE.ShapeGeometry( roundedRectShape );
};

// const createShapeGeometry = (shape: THREE.Shape): THREE.ShapeGeometry => {

// 					// flat shape with texture
// 					// note: default UVs generated by THREE.ShapeGeometry are simply the x- and y-coordinates of the vertices

// 					let geometry = new THREE.ShapeGeometry( shape );

// 					let mesh = new THREE.Mesh( geometry, new THREE.MeshPhongMaterial( { side: THREE.DoubleSide, map: texture } ) );
// 					mesh.position.set( x, y, z - 175 );
// 					mesh.rotation.set( rx, ry, rz );
// 					mesh.scale.set( s, s, s );
// 					group.add( mesh );

// 					// flat shape

// 					geometry = new THREE.ShapeGeometry( shape );

// 					mesh = new THREE.Mesh( geometry, new THREE.MeshPhongMaterial( { color: color, side: THREE.DoubleSide } ) );
// 					mesh.position.set( x, y, z - 125 );
// 					mesh.rotation.set( rx, ry, rz );
// 					mesh.scale.set( s, s, s );
// 					group.add( mesh );

// 					// extruded shape

// 					geometry = new THREE.ExtrudeGeometry( shape, extrudeSettings );

// 					mesh = new THREE.Mesh( geometry, new THREE.MeshPhongMaterial( { color: color } ) );
// 					mesh.position.set( x, y, z - 75 );
// 					mesh.rotation.set( rx, ry, rz );
// 					mesh.scale.set( s, s, s );
// 					group.add( mesh );

// 					addLineShape( shape, color, x, y, z, rx, ry, rz, s );

// 				}

// export default function createExtrudedShape(shape, extrudeSettings, color, x, y, z, rx, ry, rz, s) {

// }
